name: CI Pipeline - Infra

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init -backend=true -backend-config="bucket=${{ secrets.BUCKET_NAME }}" -backend-config="key=${{ secrets.BUCKET_PATH }}" -backend-config="region=${{ secrets.AWS_REGION }}"

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
          POSTGRES_DB_USERNAME: ${{ secrets.POSTGRES_DB_USERNAME }}
          POSTGRES_DB_PASSWORD: ${{ secrets.POSTGRES_DB_PASSWORD }}
        run: |
          terraform plan -var="AWS_REGION=${AWS_REGION}" \
                           -var="AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" \
                           -var="AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" \
                           -var="AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" \
                           -var="POSTGRES_DB_NAME=${POSTGRES_DB_NAME}" \
                           -var="POSTGRES_DB_USERNAME=${POSTGRES_DB_USERNAME}" \
                           -var="POSTGRES_DB_PASSWORD=${POSTGRES_DB_PASSWORD}"
